export const GENERATE_TELEPHONE_NUMBER_SUCCESS = 'GENERATE_TELEPHONE_NUMBER_SUCCESS';
export const GET_ALL_TELEPHONE_NUMBER_SUCCESS = 'GET_ALL_TELEPHONE_NUMBER_SUCCESS';
export const DELETE_ALL_PHONE_NUMBER_SUCCESS = 'DELETE_ALL_PHONE_NUMBER_SUCCESS';
